version: '3.9'

services:

  mysql:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./volumes/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: kmutt-library
      MYSQL_ROOT_PASSWORD: $DB_PASS

  phpmyadmin:
    image: phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: $DB_PASS
