export const bookdata = [
    {   
        bookid: 'M01',
        image: "./bookimages/chainsawman_volume_1.jpg",
        title : "Chainsawman, vol. 1",
        category: ['Action','Comedy'],
        type: 'Manga',
        publisher: 'Viz Media, Subs. of Shogakukan Inc (US)',
        publishDate: '2020-10-06',
        pages: '192',
        language: 'English',
        isbn: '9781974709939',
        author: 'Fujimoto, Tatsuki',
        description: "Denji was a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil Pochita and becomes something new and dangerous—Chainsaw Man! Denji's a poor young man who'll do anything for money, even hunting down devils with his pet devil Pochita. He's a simple man with simple dreams, drowning under a mountain of debt. But his sad life gets turned upside down one day when he's betrayed by someone he trusts. Now with the power of a devil inside him, Denji's become a whole new man—Chainsaw Man!",
        location: 'Floor 2, bookshelf 4L'
    },
    {   
        bookid: 'M02',
        image: "./bookimages/kaguya_sama_love_is_war_volume_1.jpg",
        title : "Kaguya sama love is war, vol. 1",
        category: ['Comedy','Romance'],
        type: 'Manga',
        publisher: 'Viz Media, Subs. of Shogakukan Inc (US)',
        publishDate: '2018-03-06',
        pages: '216',
        language: 'English',
        isbn: '9781974700301',
        author: 'Akasaka, Aka',
        description: "All's fair when love is war! Two prideful geniuses locked in battle. Who will make the first misstep and in doing so...confess their love? Kaguya Shinomiya and Miyuki Shirogane are two geniuses who stand atop their prestigious academy's student council, making them the elite among elite. But it's lonely at the top and each has fallen for the other. There's just one huge problem standing in the way of lovey-dovey bliss—they're both too prideful to be the first to confess their romantic feelings and thus become the 'loser' in the competition of love! And so begins their daily schemes to force the other to confess first! A romantic comedy featuring the hilarious antics of geniuses in love.",
    },
    {   
        bookid: 'M03',
        image: "./bookimages/chainsawman_volume_5.jpg",
        title : "Chainsawman, vol. 5",
        category: ['Action','Comedy'],
        type: 'Manga',
        publisher: 'Viz Media, Subs. of Shogakukan Inc (US)',
        publishDate: '2021-06-01',
        pages: '200',
        language: 'English',
        isbn: '9781974719228',
        author: 'Fujimoto, Tatsuki',
        description: "Denji’s a poor young man who’ll do anything for money, even hunting down devils with his pet devil Pochita. He’s a simple man with simple dreams, drowning under a mountain of debt. But his sad life gets turned upside down one day when he’s betrayed by someone he trusts. Now with the power of a devil inside him, Denji’s become a whole new man—Chainsaw Man!",
    },
    {   
        bookid: 'M04',
        image: "./bookimages/Miss_Kobayashi's_Dragon_Maid_Volume_1.jpg",
        title : "Miss kobayashi's Dragon maid, vol. 1",
        category: ['Comedy','Slice of life'],
        type: 'Manga',
        publisher: 'Seven Seas Entertainment',
        publishDate: '2016-10-18',
        pages: '144',
        language: 'English',
        isbn: '9781626923485',
        author: 'Coolkyousinnjya',
        description: "Miss Kobayashi's Dragon Maid is a delightful, ongoing comedy manga series about a young lady who, after saving a dragon's life, finds herself the object of its indebtedness and undying affection. Featuring a cast of colourful supernatural characters, Miss Kobayashi's Dragon Maid is the perfect book for fans of Monster Musume and Merman in my Tub. Miss Kobayashi's Dragon Maid will be released as single-volume books, each including a full-colour insert. Miss Kobayashi is your average office worker who lives alone in her small apartment-until a young and adorable dragon girl named Tooru appears before her. Upon saving Tooru's life, the fiesty dragon will do anything to pay off her debt of gratitude, including insisting that she move in with Miss Kobayashi and serve her in any way she does or doesn't desire. Now Miss Kobayashi finds herself with a new, imposing roommate, who is doing her best to help out around the home. But when you're a dragon, nothing is ever simple. Kobayashi's normal life just went off the deep end.",
    },
    {   
        bookid: 'M05',
        image: "./bookimages/dr_stone_volume_1.jpg",
        title : "Dr.stone, vol. 1",
        category: ['Action','Science','Comedy'],
        type: 'Manga',
        publisher: 'VIZ Media LLC',
        publishDate: '2018-09-04',
        pages: '200',
        language: 'English',
        isbn: '9781974702619',  
        author: 'Riichiro Inagaki',
        description: "One fateful day, all of humanity was petrified by a blinding flash of light. After several millennia, high-schooler Taiju awakens and finds himself lost in a world of statues. However, he’s not alone! His science-loving friend Senku’s been up and running for a few months and he's got a grand plan in mind—to kickstart civilization with the power of science!",
    },
    {   
        bookid: 'M06',
        image: "./bookimages/spy_x_family_volume_1.jpg",
        title : "Spy x family, vol. 1",
        category: ['Action','Comedy'],
        type: 'Manga',
        publisher: 'VIZ Media LLC',
        publishDate: '2020-06-02',
        pages: '220',
        language: 'English',
        isbn: '9781974715466',  
        author: 'Tatsuya Endo',
        description: "Master spy Twilight is unparalleled when it comes to going undercover on dangerous missions for the betterment of the world. But when he receives the ultimate assignment—to get married and have a kid—he may finally be in over his head!",
    },
    {   
        bookid: 'M07',
        image: "./bookimages/onimai_i'm_now_your_sister_volume_1.jpg",
        title : "Onimai I'm now your sister, vol. 1",
        category: ['Comedy','Slice of life'],
        type: 'Manga',
        publisher: 'Kodansha Comics',
        publishDate: '2021-08-31',
        pages: '179',
        language: 'English',
        isbn: '9781636993362',  
        author: 'Nekotofu',
        description: "Mahiro Oyama was just a normal erotic-game loving dude... until he woke up one morning as a woman! Turns out his mad-scientist little sister, Mihari, tried out one of her new experiments on him... with a disastrous outcome, as far as Mahiro's concerned! But Mihari is as determined to study him as he is determined to go back to his shut-in, game-playing life, and one thing's for sure... life is going to get a whole lot weirder from here on out!",
    },
    {   
        bookid: 'M08',
        image: "./bookimages/bocchi_the_rock_volume_1.jpg",
        title : "Bocchi the rock, vol. 1",
        category: ['Comedy','Slice of life','Music'],
        type: 'Manga',
        publisher: 'Houbunsha',
        publishDate: '2019-02-27',
        pages: '124',
        language: 'Japanese',
        isbn: '9784832270725', 
        author: 'Aki Hamaji',
        description: "Goto Hitori, aka 'Bokuchi-chan' is a lonely girl who loves to play the guitar. She spends her days playing alone at home, but by chance, she joins the 'Band of Unity' led by Nijika Ijichi. Goto is not used to performing in front of others, but can she become a great band member? This is the hottest music manga for all the chubby boys and girls in Japan right now!",
    },
    {   
        bookid: 'L01',
        image: "./bookimages/that_time_i_got_reincarnated_as_a_slime_volume_1.jpeg",
        title : "That Time I Got Reincarnated as a Slime, Vol. 1",
        category: ['Comedy','Fantasy','Isekai'],
        type: 'Light novel',
        publisher: 'Yen On',
        publishDate: '2017-12-19',
        pages: '292',
        language: 'English',
        isbn: '9780316414203', 
        author: 'Fuse',
        description: "Lonely thirty-seven-year-old Satoru Mikami is stuck in a dead-end job, unhappy with his mundane life, but after dying at the hands of a robber, he awakens to a fresh start in a fantasy realm...as a slime monster! As he acclimates to his goopy new existence, his exploits with the other monsters set off a chain of events that will change his new world forever!",
    },
    {   
        bookid: 'M09',
        image: "./bookimages/little_witch_academia_volume_1.jpg",
        title : "Little witch academia, Vol. 1",
        category: ['Comedy','Fantasy','Slice of life'],
        type: 'Manga',
        publisher: 'JY',
        publishDate: '2018-06-26',
        pages: '176',
        language: 'English',
        isbn: '9781975327453', 
        author: 'Yoh Yoshinari',
        description: "Those words changed young Atsuko 'Akko' Kagari forever, sparking in her a lifelong dream of becoming a real witch. Now she's been accepted to the same school as her childhood hero, Shiny Chariot-the prestigious Luna Nova Witchcraft Academy. As the only student to come from a non-magical family, Akko finds herself surrounded by prodigies from around the world, but giving up isn't in her vocabulary. Whether it's making friends, proving the doubters wrong, or just flying on a broom, Akko is going to make her fantasy a reality!"
    },
    {   
        bookid: 'M11',
        image: "./bookimages/lycoris_recoil_volume_1.jpg",
        title : "Lycoris recoil, Vol. 1",
        category: ['Comedy','Action','Slice of life'],
        type: 'Manga',
        publisher: 'Kadokawa',
        publishDate: '2022-09-05',
        pages: '176',
        language: 'Japanese',
        isbn: '9784046820303', 
        author: 'Spider Lily',
        description: `This is a small description depicting the everyday extraordinary life of Cafe Rico Rico!
        "Welcome to Cafe Licorico!"
        　A stylish and delicious cafe on the east side of Tokyo overlooking the destroyed old radio tower - that is Cafe LicoRico.
        　This work is a little description of ordinary extraordinary things woven by signboard girls such as Senzoku Nishiki and Takina Inoue, which were not drawn in the original TV animation "Lycoris Recoil". Delicious sweets, gun action, games, human drama, zombies and monsters, road movies ...
        　and a faint love 　!? As they go on, their bonds are born--the original creator himself turned into a spin-off novel of an assortment of anything like a variety pack of sweets with bonuses!`
      },
      {   
        bookid: 'M10',
        image: "./bookimages/girls_last_tour_volume_1.jpg",
        title : "Girl's last tour, Vol. 1",
        category: ['Adventure','Drama'],
        type: 'Manga',
        publisher: 'Yen Press; Illustrated edition',
        publishDate: '2017-05-23',
        pages: '160',
        language: 'English',
        isbn: '9780316470629', 
        author: 'Tsukumizu',
        description: "Civilization is dead, but not Chito and Yuuri. Time to hop aboard their beloved Kettenkrad motorbike and wander what's left of the world! Sharing a can of soup or scouting for spare parts might not be the experience they were hoping for, but all in all, life isn't too bad..."
      },
      {   
        bookid: 'M12',
        image: "./bookimages/bofuri_volume_1.jpeg",
        title : "Bofuri: I Don't Want to Get Hurt, so I'll Max Out My Defense, Vol. 1",
        category: ['Fantasy','Adventure','Drama'],
        type: 'Manga',
        publisher: 'Yen Press',
        publishDate: '2021-05-04',
        pages: '164',
        language: 'English',
        isbn: '9781975323868', 
        author: 'Yuumikan',
        description: "Civilization is dead, but not Chito and Yuuri. Time to hop aboard their beloved Kettenkrad motorbike and wander what's left of the world! Sharing a can of soup or scouting for spare parts might not be the experience they were hoping for, but all in all, life isn't too bad..."
      },
      {   
        bookid: 'M13',
        image: "./bookimages/jojo_part_3_volume_1.jpg",
        title : "JoJo's Bizarre Adventure: Part 3 Stardust Crusaders, Vol. 1",
        category: ['Fantasy','Adventure','Action'],
        type: 'Manga',
        publisher: 'VIZ Media LLC',
        publishDate: '2016-11-01',
        pages: '320',
        language: 'English',
        isbn: '9781421590653', 
        author: 'Hirohiko Araki',
        description: "The legendary Shonen Jump series is now available in deluxe editions featuring color pages and newly drawn cover art! JoJo’s Bizarre Adventure is a groundbreaking manga famous for its outlandish characters, wild humor and frenetic battles. The beginning of the Stardust Crusaders Arc! A fiendish villain once thought to be dead has resurfaced and become even more powerful! To fight this evil, the aging Joseph Joestar enlists the help of his hot-blooded grandson, Jotaro Kujo. Together they embark on a perilous adventure that will take them around the world! "
      },
      {   
        bookid: 'M14',
        image: "./bookimages/komi_cant_communicate_volume_1.jpg",
        title : "Komi Can't Communicate, Vol. 1",
        category: ['Fantasy','Adventure','Action'],
        type: 'Manga',
        publisher: 'VIZ Media LLC',
        publishDate: '2019-06-11',
        pages: '192',
        language: 'English',
        isbn: '9781974707126', 
        author: 'Tomohito Oda',
        description: "Socially anxious high school student Shoko Komi’s greatest dream is to make some friends, but everyone at school mistakes her crippling social anxiety for cool reserve! With the whole student body keeping their distance and Komi unable to utter a single word, friendship might be forever beyond her reach."
      },
]